### ISSUE TITLE
expose `got` as decorator

### ISSUE THREAD

**Issue by Kikobeats** [sayem314/hooman#1]
Hello,

Do you think it could be possible to expose a more affordable interface in order to prevent get `got` locked by this package?

This is the thing I have on mind:

```js
const got = require('hooman')(require('got')
```

**Comment by sayem314** [comment]
It's possible with peer dependencies but anything wrong this locked version to latest?

**Comment by Kikobeats** [comment]
Jut suggesting because `got` tends to release new versions very often.

Locking to 11.x version isn't the best approach, they sometimes introduce bug accidentally.

Using the decoratr approach you're moving the responsibility out of the library.

**Comment by sayem314** [comment]
Will provide it as a peer dependency on next version :)

**Comment by Kikobeats** [comment]
Thanks a lot!
