### ISSUE TITLE
Stopped bypass

### ISSUE THREAD

**Issue by andress134** [sayem314/hooman#11]
#### What would you like to discuss?

With new version my script stoped working, we need to update or any bug ?
Just spamming  console with html and get error Response code 403 (Forbidden)

here is my script

https://pastebin.com/raw/WAc5LLjS 

#### Checklist

- [x] I have read the hooman and got documentation.

**Comment by sayem314** [comment]
First init cookie with a sample request and then provide further requests.

**Comment by andress134** [comment]
> First init cookie with a sample request and then provide further requests.

I don't know what is wrong, hmm
Also, about captcha, i see can't bypass

this is my code for bypass, i know all is good

`function send_req() {

  return new Promise((resolve, reject) => {
    hooman.get(target, {
      captchaKey: 'key',
      rucaptcha: true | false, // optional (default false)
        });
        console.log(response.body);
        return reject(error.message);
      });
}

setInterval(() => {
    send_req();
})`

[info] Solving hcaptcha at https://exitus.xyz/
[info] Solving hcaptcha at https://exitus.xyz/
[info] Solving hcaptcha at https://exitus.xyz/
[info] Solving hcaptcha at https://exitus.xyz/

get it but don't bypass

**Comment by sayem314** [comment]
rucaptcha: true | false, // optional (default false) < remove this line

**Comment by andress134** [comment]
> rucaptcha: true | false, // optional (default false) < remove this line

same, just waiting 3 mins and nothing, just send me messages

[info] Solving hcaptcha at https://exitus.xyz/

`function send_req() {

  return new Promise((resolve, reject) => {
    hooman.get(target, {
      captchaKey: 'key',
        });
        console.log(response.body);
        return reject(error.message);
      });
}

setInterval(() => {
    send_req();
});`

**Comment by sayem314** [comment]
Use it like this:

const hooman = require('hooman');

```js
(async () => {
  try {
    const response = await hooman.get('https://exitus.xyz/'); // set cookie
    setInterval(() => {
      send_req();
    }, 1000);
  } catch (error) {
    console.log(error.response.body);
  }
})();
```

**Comment by andress134** [comment]
> ```js
> console.log(error.response.body);
> ```

the uam work fine now without proxies, with proxies just get captcha error

about captcha, still can't bypass, with old verion tried on other server, is working but use to much $ balance, with new vers, just  i'm waiting
https://pastebin.com/raw/UbwP14Ti  this is full code

also I really appreciate your work and your help, I would love to donate, but unfortunately I do not use paypal, if you add donations with bitcoin

**Comment by andress134** [comment]
> Use it like this:
> 
> const hooman = require('hooman');
> 
> ```js
> (async () => {
>   try {
>     const response = await hooman.get('https://exitus.xyz/'); // set cookie
>     setInterval(() => {
>       send_req();
>     }, 1000);
>   } catch (error) {
>     console.log(error.response.body);
>   }
> })();
> ```

the uam work fine now without proxies, with proxies just get captcha error

about captcha, still can't bypass, with old verion tried on other server, is working but use to much $ balance, with new vers, just i'm waiting
https://pastebin.com/raw/UbwP14Ti this is full code

also I really appreciate your work and your help, I would love to donate, but unfortunately I do not use paypal, if you add donations with bitcoin

**Comment by andress134** [comment]
Have updated, the script send first 40 req and stop

**Comment by sayem314** [comment]
I'm still working on it...

**Comment by sayem314** [comment]
BTW thanks for considering a donation :) You can re-visit my donation page, added BTC. Thanks.

**Comment by sayem314** [comment]
Pushed the latest commits. Can you please give it a try and let me know now?

**Comment by andress134** [comment]
> Pushed the latest commits. Can you please give it a try and let me know now?

still same for me, first requsts are sending, aftger 60 secounds send first request one time and stopped

i think some error on multi requests, can't send unlimited requests or idk
https://pastebin.com/raw/Am5t6tw2 my code look good (with old vers still work fine but using to much $)

**Comment by sayem314** [comment]
I believe something is wrong on your side. Please take a look at this stream, everything works as expected and I have nothing else to modify to make it better.

https://streamable.com/nab65a

**Comment by sayem314** [comment]
Also, you are not supposed to make unlimited requests to a site, it's DDoS and hooman is not meant for that. Hooman exists for legal scraping reasons, you should only use it sanely. BTW when you make thousands of requests you should ensure that your system could handle that with regulars sites as well, making too much requests at a time would cause connection reset error if your system resource including network is not stable enough.

**Comment by maximus99-art** [comment]
> Also, you are not supposed to make unlimited requests to a site, it's DDoS and hooman is not meant for that. Hooman exists for legal scraping reasons, you should only use it sanely. BTW when you make thousands of requests you should ensure that your system could handle that with regulars sites as well, making too much requests at a time would cause connection reset error if your system resource including network is not stable enough.

same problem for me, i get new version but stoped bypass using multi requests

for uam receive error: Response code 403 (Forbidden) and for captcha status 200
cloudflare use tls  1.2/1.3 to secure conexion
About 'multi requests, want to use your script to generate fake traffic (view)  (TE) on my website, and to vote, so my script select a proxy and conect to website solve captcha and click vote.
So i can't use your script for it ? generating multi requests ?

**Comment by sayem314** [comment]
@maximus99-art use node.js >=12. captcha bypass with multiple proxies might increase captcha triggering by a lot.

**Comment by sayem314** [comment]
And btw if you click vote on your own sites,  why so hurry? Why not vote one by one using await? Like this:

```js
while (true) {
  await vote();
}
```

**Comment by maximus99-art** [comment]
> And btw if you click vote on your own sites, why so hurry? Why not vote one by one using await? Like this:
> 
> ```js
> while (true) {
>   await vote();
> }
> ```

it's about a contest that is updated every 1 hour until it reaches the finals, I have to get a lot of votes
every one hour someone is eliminated until only 1 winner remains

now get this using http proxies

`Response code 400 (Bad Request)
Response code 503 (Service Unavailable)
certificate has expired
unable to verify the first certificate`

**Comment by sayem314** [comment]
`hooman(url, { rejectUnauthorized: false })`

**Comment by maximus99-art** [comment]
> hooman(url, { rejectUnauthorized: false })

most cloudflare sites check via tls to be able to secure the connection

tried to edit my script like

`hooman(vote, {
      captchaKey: 'captcha-key',
      rejectUnauthorized: false,
      APLNProtocols: ['http/1.1', 'http/1.0'],
      })
    .then((res) => {
    })
    .catch((err) => {
    console.log('error: ' + err.message);
});
};`
first bypass working fine, but next bypass stoped, or ask for  tls to secure conexion, also spamming with html and get memory leak

`0: ExitFrame [pc: 0x13da519]
Security context: 0x17746a880921 <JSObject>
    1: assign(aka assign) [0x17746a881249](this=0x26e0cfac04b9 <undefined>,0x13caba9b67f1 <Object map = 0x259e441175a1>,0x1d6018485bc9 <Object map = 0x248850ef8bb1>)
    2: _makeRequest [0x1be705181e09] [/root/node_modules/got/dist/source/core/index.js:~846] [pc=0x323ece6225b9](this=0x1d6018485961 <Duplex map = 0x259e441197b1>)
    3: /* anonymous */ [0x1d60184b9...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
`

idk why because my vps is good, 8 gb ram, 1 gbit conexion

**Comment by sayem314** [comment]
Please use nodejs 12 or later, it uses tls 1.2 by default otherwise see here https://nodejs.org/api/cli.html#cli_tls_min_v1_2

1. And how many requests are you making to the same domain at a time?
2. Are you using proxy?
3. How many proxies are you using? What do you mean by spamming HTML?
4. Does got works with regular websites with same config?

**Comment by maximus99-art** [comment]
Im using nodejs v14.2
Tried with proxi and without, same
If i put the console.log the script show me the html content of website on my console
My script send 10 requests, (if im using proxies) he select 10 random http proxies and conect it,  'sleep for 30 sec' and send again 10 req
Same config has working fine with old version of hooman
only the script spam with captcha requests and consumes your entire balance

**Comment by sayem314** [comment]
It works fine on my side. I cannot reproduce the issue. Can't help with multiple proxy + captcha.
https://streamable.com/nab65a
