### ISSUE TITLE
Download image throught clouflare with pipe send error 503

### ISSUE THREAD

**Issue by Clemv95** [sayem314/hooman#12]
Here is my code : `var fs = require('fs')
const request = require('request');
const emojis = require('./emojis.json');
const hooman = require('hooman');

var download = async function(uri, filename, callback) {
    var file = fs.createWriteStream(filename);
    var r = hooman.stream(uri).pipe(file);
    r.on('error', function(err) { console.log(err); });
    r.on('finish', function() { file.close(callback) });
};

for (let i = 0; i < emojis.length; i++) {
    nom = emojis[i].image.slice(emojis[i].image.indexOf("emoji/") + 6, emojis[i].image.length);
    download(emojis[i].image, "./emojis/" + nom, function(err) {
        console.log(err);
    })

}`

And here is the error 
![image](https://user-images.githubusercontent.com/32482023/81835568-b24d1e00-9542-11ea-82d3-f77c5c2fe372.png)

**Comment by sayem314** [comment]
You are suppose to respect issue template when creating issue, the template exists for a reason. BTW stream example is documented here > https://github.com/sayem314/hooman#pipe-stream

**Comment by sayem314** [comment]
Related issue you can read on to grasp more details: https://github.com/sayem314/hooman/issues/3

**Comment by Clemv95** [comment]
Yeah sorry about that it's m'y first issue on github.
I dont understand what is the await lign for pipe can you help ?

**Comment by sayem314** [comment]
@Clemv95 no problem then.

you can use it like this:

```js
const fs = require('fs');
const request = require('request');
const emojis = require('./emojis.json');
const hooman = require('hooman');

const download = async function(uri, filename, callback) {
  let file = fs.createWriteStream(filename);
  let r = hooman.stream(uri).pipe(file);
  r.on('error', function(err) {
    console.log(err);
  });
  r.on('finish', function() {
    file.close(callback);
  });
};

hooman
  .get(siteUrl)
  .then((res) => {
    for (let i = 0; i < emojis.length; i++) {
      nom = emojis[i].image.slice(emojis[i].image.indexOf('emoji/') + 6, emojis[i].image.length);
      download(emojis[i].image, './emojis/' + nom, function(err) {
        console.log(err);
      });
    }
  })
  .catch((err) => {
    console.log(err.message);
  });
```

`siteUrl` is the main base url of images where you will download images from. first you make dummy request to initialize cookie.

**Comment by sayem314** [comment]
You can also use this function for image/small binary files.

```js
const download = async function(uri, filename, callback) {
  try {
    const { body } = await hooman.get(uri, {
      responseType: 'buffer',
    });
    // Write image to file
    fs.writeFileSync('image.jpg', body);
    console.log('Done');
  } catch (err) {
    callback(err);
  }
};
```

**Comment by sayem314** [comment]
Quick full example based your code:

```js
const fs = require('fs');
const request = require('request');
const emojis = require('./emojis.json');
const hooman = require('hooman');

const download = async function(uri, filename, callback) {
  try {
    const { body } = await hooman.get(uri, {
      responseType: 'buffer',
    });
    // Write image to file
    fs.writeFileSync(filename, body);
    callback();
  } catch (err) {
    callback(err);
  }
};

for (let i = 0; i < emojis.length; i++) {
  nom = emojis[i].image.slice(emojis[i].image.indexOf('emoji/') + 6, emojis[i].image.length);
  download(emojis[i].image, './emojis/' + nom, function(err) {
    console.log(err);
  });
}
```
