### ISSUE TITLE
Cloudflare seem to change their technology

### ISSUE THREAD

**Issue by tambdc-self** [sayem314/hooman#19]
#### Describe the bug

- Hooman version: 1.2.5
- Node.js version: 12.17.0
- OS & version:win10

Be able to require web page (http://www.javlibrary.com/)

> write here

get an error

> write here

const Humanoid = require("@subns/humanoid-js");
 
let humanoid = new Humanoid();
humanoid.get("http://www.javlibrary.com/")
    .then(res => {
    	console.log(res.body) // <!DOCTYPE html><html lang="en">...
    })
    .catch(err => {
    	console.error(err)
    })

#### Checklist

- [ X ] I have tried my code with the latest version of Node.js and hooman.

**Comment by sayem314** [comment]
Why are you using hooman with `new` operator? Hooman is not a constructor. BTW the mentioned site worked fine for me.
