### ISSUE TITLE
spamming with html content

### ISSUE THREAD

**Issue by andress134** [sayem314/hooman#20]
#### Describe the bug

- Hooman version: 1.2.5
- Node.js version: v14.3.0
- OS & version: Debian 9

#### Actual behavior

I try to bypass uam, but hooman just get html content and spamming my vps
proof https://prnt.sc/sqd3u9
tested url  https://botflare.xyz

#### Expected behavior

> write here

#### Code to reproduce

```js
function send_req() {
  let proxy = proxies[Math.floor(Math.random() * proxies.length)];
  proxy = new HttpsProxyAgent('http://' + proxy);

return new Promise((resolve, reject) => {
hooman.get(url, {
      agent: {
        https: proxy,
      },
      cloudflareRetry: 5,
    })
      .then(response => {
        resolve(response);
      })
      .catch((error) => {
      console.log(error.response.body);
        let obj_v = proxies.indexOf(proxy);
        proxies.splice(obj_v, 1);
        console.log(error.message);
        return reject(error.message);
      });
  });
}

setInterval(() => {
    send_req();
})
```

#### Checklist

- [x] I have tried my code with the latest version of Node.js and hooman.

**Comment by sayem314** [comment]
403 === captcha. Did you check with `captchaKey`? Also, why are you printing error body, this is why console was spammed.

**Comment by andress134** [comment]
> 403 === captcha. Did you check with `captchaKey`? Also, why are you printing error body, this is why console was spammed.

I know 403 is captcha, but the target url is not capcha, is uam, also, if will remove the
