### ISSUE TITLE
Need some help if is posible

### ISSUE THREAD

**Issue by Danny1994d** [sayem314/hooman#22]
#### What would you like to discuss?

Hello, i dont know what is wrong, can't bypass hcaptcha, just im waiting 1-3 min and nothing

my exemple code

```js
const hooman = require('hooman');
const url= process.argv[2];
  return new Promise((resolve, reject) => {
    hooman.get(url, {
      captchaKey: 'key',
    });
    })
      .catch((error) => {
      console.log(error.message);
      return reject(error.message);
      });
      }
```
#### Checklist

- [x] I have read the hooman and got documentation.

**Comment by sayem314** [comment]
did you provide real captchaKey from 2captcha?

**Comment by sayem314** [comment]
and did you get any message like `[info] Solving hcaptcha at {pageurl}`

**Comment by Danny1994d** [comment]
> did you provide real captchaKey from 2captcha?

Yes, i have provide real key, and yes, just console log 'solving hcaptcha etc'' but im waiting up to 3 mins and nothing
Test url : https://habnet.biz/ and https://runo.pw/

**Comment by sayem314** [comment]
maybe captcha workers are busy. for now, use this one. please don't abuse it. it's free btw. and captcha key is really `dummy`

```js
captchaKey: 'dummy',
captchaRetry: 2,
onCaptcha: async ({ pageurl, sitekey, method }) => {
  try {
    console.log(`[info] Solving ${method} at ${pageurl} for free!`);
    const { body } = await hooman.post('https://harvest.caddy.eu.org/solve', {
      json: {
        sitekey,
        pageurl,
      },
      responseType: 'json',
    });
    return body.generated_pass_UUID;
  } catch (e) {
    console.log(e.message);
  }
},
```
