### ISSUE TITLE
Can't bypass CF Bot Fight Mode

### ISSUE THREAD

**Issue by Danny1994d** [sayem314/hooman#24]
#### Describe the bug

- Hooman version: 1.2.5
- Node.js version: v14.4.0
- OS & version: Debian 9

#### Actual behavior

Hello im try to bypass a uam + bot fight mode, and can't, hooman can't do it?
Tested URL :  https://audiograb.net/

//edit : url some times use uam + captcha (not for all ips, if im using vpn work just on uam)
How can use hooman to bypass uam + captcha in same time, can do it?

#### Expected behavior

> write here

#### Code to reproduce

```js
return new Promise((resolve, reject) => {
hooman.get(url, {
      agent: {
        https: proxy,
      },
      cloudflareRetry: 10,
    })
      .then(response => {
        resolve(response);
      })
      .catch((error) => {
      console.log(error.response.body);
        let obj_v = proxies.indexOf(proxy);
        proxies.splice(obj_v, 1);
        console.log(error.message);
        return reject(error.message);
      });
  });
}
```

#### Checklist

- [x] I have tried my code with the latest version of Node.js and hooman.

**Comment by sayem314** [comment]
You need to provide `captchaKey` from 2captcha. Hooman automatically bypasses both challenges at the same URL.

**Comment by Danny1994d** [comment]
> You need to provide `captchaKey` from 2captcha. Hooman automatically bypasses both challenges at the same URL.

I tried to add 2captcha key, but i get error, hooman dont found the hcaptcha on url, just starting to bypass uam
And get error

`write EPROTO 139647672223616:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

socket hang up
Client network socket disconnected before secure TLS connection was established
socket hang up
Client network socket disconnected before secure TLS connection was established
`

exemple code 

```js
return new Promise((resolve, reject) => {
hooman.get(target, {
      captchaKey: 'key',
      agent: {
        https: proxy,
      },
      cloudflareRetry: 10,
    })
      .then(response => {
        resolve(response);
      })
      .catch((error) => {
        let obj_v = proxies.indexOf(proxy);
        proxies.splice(obj_v, 1);
        console.log(error.message);
        return reject(error.message);
      });
  });
}```

**Comment by sayem314** [comment]
Looks like the error is from your proxy provider. Please set `rejectUnauthorized` to false on proxy-agent. This is not an error with hooman, you can try this with bare got library and then either open an issue on got or proxy-agent repo.

**Comment by Danny1994d** [comment]
> Looks like the error is from your proxy provider. Please set `rejectUnauthorized` to false on proxy-agent. This is not an error with hooman, you can try this with bare got library and then either open an issue on got or proxy-agent repo.
@sayem314 sayem314
Just a problem sir, why if im removing  console.log(error.response.body);  script stoped bypass, but if i still add console.log(error.response.body); bypass work, but server is spammed with html content

**Comment by sayem314** [comment]
`error.response.body` contains HTML of challenge page, not the actual HTML you might be looking for. Take a good look at the source.

**Comment by Danny1994d** [comment]
> `error.response.body` contains HTML of challenge page, not the actual HTML you might be looking for. Take a good look at the source.

Oke sir, will check again, but i know is the new challenge of cloudflare, i know has updated again, becaue now all websites get a free captcha and browser verification when detect bad requests
