### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by Tienza** [sayem314/hooman#27]
#### What would you like to discuss?
Nothing is being printed when I invoke this code.

node: v10.14.0
hooman: v1.2.5
OS: Windows 10

```javascript
const hooman = require('hooman');

(async () => {
    try {
        const response = await hooman.get('https://kissmanga.com/Manga/Grand-Blue');
        console.log(response.body);
        console.log('I succeed');
        //=> '<!doctype html> ...'
    } catch (error) {
        console.log(error.response.body);
        console.log('I failed');
        //=> 'Internal server error ...'
    }
})();
```

#### Checklist

- [x] I have read the hooman and got documentation.

**Comment by sayem314** [comment]
![image](https://user-images.githubusercontent.com/14138401/84398939-5f8a8300-ac22-11ea-80b2-ddb8ddef52b4.png)

works fine.

**Comment by Tienza** [comment]
Thanks for the quick reply!

![image](https://user-images.githubusercontent.com/10120331/84399773-3c82b380-abcf-11ea-81a6-78ad4d7485b2.png)

Any idea why this might be happening on my end?

**Comment by sayem314** [comment]
Not sure. You must be doing something wrong on your final code, please recheck the code.

**Comment by Tienza** [comment]
The posted code is all I have, nothing has changed.
![image](https://user-images.githubusercontent.com/10120331/84400088-9b482d00-abcf-11ea-90ff-977858f29154.png)

**Comment by sayem314** [comment]
why you are using `nodejs`? shouldn't it be `node`?

**Comment by Tienza** [comment]
Oh, I must have pressed tab too make times for autocomplete. That was the issue. Thank you so much!

**Comment by Tienza** [comment]
I'm getting "No captcha answer" response when trying the code on a slightly different link. I cannot get the captcha key from browser because when I use the browser there is no captcha request.

![image](https://user-images.githubusercontent.com/10120331/84416818-b96b5880-abe2-11ea-89d8-ca68c0e883f5.png)
![image](https://user-images.githubusercontent.com/10120331/84416911-dbfd7180-abe2-11ea-9bee-a36689762b3a.png)

**Comment by sayem314** [comment]
The site is using custom captcha. You need to build your own solver for that. Nothing to do with hooman.

**Comment by Tienza** [comment]
Thank you for the help :)
