### ISSUE TITLE
How to download an image behind cloudflare?

### ISSUE THREAD

**Issue by linaspasv** [sayem314/hooman#3]
I am trying the following and get 415 (Unsupported Media Type) error.

```javascript
const got = require("hooman")

got('https://c.pxhere.com/images/11/49/74e4a31de6abe70227fa1cb22d37-1612083.jpg!d')
    .then(response => {
        console.log(response);
    })
    .catch(error => {
        console.error(error);
    });
```

**Comment by sayem314** [comment]
use `responseType` as `buffer`

Docs:
https://github.com/sindresorhus/got#responsetype

Example:
```js
const { body}  = await got(url, { responseType: 'buffer' });
```

**Comment by sayem314** [comment]
You can also pipe stream to file.

```js
const { createWriteStream } = require("fs");
const got = require("hooman");

(async () => {
  const image = createWriteStream("image.jpg");
  got
    .stream("https://c.pxhere.com/images/11/49/74e4a31de6abe70227fa1cb22d37-1612083.jpg!d")
    .pipe(image);
})();

```

**Comment by linaspasv** [comment]
Hm, still getting 415 (Unsupported Media Type) :/

```javascript
const got = require("hooman");

let url = "https://c.pxhere.com/images/11/49/74e4a31de6abe70227fa1cb22d37-1612083.jpg!d"

got(url, { responseType: 'buffer' }).then(response => {
    console.log(response.body)
})
```

**Comment by sayem314** [comment]
@linaspasv can you please try stream example I posted later? Also, this library is just a wrapper around got to bypass Cloudflare js-challenge,  request related issues are best to first test with got library and open issue over there.

**Comment by linaspasv** [comment]
With the stream example I get 503 (Service Unavailable) error.

**Comment by linaspasv** [comment]
The image I am trying to access is under cloudflare anti-ddos protection page. I have tried your script with the regular HTML page and it works perfectly but fails for a direct image download. I am not sure if it's issue with this library or got library.

![image](https://user-images.githubusercontent.com/1407067/81479557-9f79d700-922c-11ea-958c-68480294ba9f.png)

**Comment by sayem314** [comment]
I have locally tested it and it works fine for me. In fact, I have gone ahead and added this on the test and it seems to be passing as well. https://github.com/sayem314/hooman/commit/f9aa0e5b048bdff50cb6a0b8de31ebc18ee83110

**Comment by linaspasv** [comment]
Do you get challenged by cloudflare? Wwhen I run the same code (see below) on an image that has no cloudflare protection it works perfectly. pxhere.com does not give a challenge page for residential IP addresses but when you run this on some servers you get challenged. :-)

```javascript
const got = require('hooman');
const fs = require('fs');

(async () => {

    //let resource = 'https://c.pxhere.com/images/11/49/74e4a31de6abe70227fa1cb22d37-1612083.jpg!d';
    let resource = 'https://explorecams.com/storage/photos/GdmaI9FIbe_1600.jpg';

    got.stream(resource)
        .on('error', err => console.log(err))
        .pipe(
            fs.createWriteStream('image.jpg')
        )
})();
```

**Comment by sayem314** [comment]
I have tested on residential ip where their main domain did not throw js-challenge and so I have gone ahead and tested on my own Cloudflare challenge activated domain where js-challenges are always thrown.

Test code:

```js
const test = require("tape");
const scrape = require("hooman");
const { writeFileSync, statSync } = require("fs");

const jsChallengePage = "https://cf-js-challenge.sayem.eu.org";

// Test image download
test("sample image download", async t => {
  console.time("image download");
  const { body } = await scrape(jsChallengePage + "/images/background.jpg", {
    responseType: "buffer"
  });
  console.timeEnd("image download");

  // Write to file
  t.ok(Buffer.isBuffer(body));
  writeFileSync("image.jpg", body);

  // Check image size
  const { size } = statSync("image.jpg");
  t.equal(size, 31001);
});
```

> Note that I have removed other tests for fair testing result.

Test result with console log for easy debugging:
![image](https://user-images.githubusercontent.com/14138401/81480782-977e5f00-924d-11ea-9611-94bd5bf9ab22.png)

* Btw travis test are done from datacenter ip.

Here is updated test code and results:
https://github.com/sayem314/hooman/commit/9776a070fc12b2c69ce6169ceaf14671363c8dde

**Comment by sayem314** [comment]
A possible fix for you. I'm not sure what's causing you issue but give this a try:

```js
const got = require('hooman');
const fs = require('fs');

(async () => {
    await got('https://explorecams.com') // init cookie

    let resource = 'https://explorecams.com/storage/photos/GdmaI9FIbe_1600.jpg';
    got.stream(resource)
        .on('error', err => console.log(err))
        .pipe(
            fs.createWriteStream('image.jpg')
        )
})();
```

**Comment by linaspasv** [comment]
No luck. Also, I have tried to run the same without hooman (see the source code below) and I end up with the same Response code 503 (Service Temporary Unavailable) error. 
![image](https://user-images.githubusercontent.com/1407067/81482039-d0fa9e80-923c-11ea-9282-402d3f7b4298.png)

I have also tried to just curl and I get the challenge page code... so it seems your plugin is not triggered to solve the challenge page when I run this particular URL.

![image](https://user-images.githubusercontent.com/1407067/81482054-f687a800-923c-11ea-9458-147a23b31eff.png)


```javascript
const got = require('got');
const fs = require('fs');

(async () => {
    let resource = 'https://' + escape('c.pxhere.com/images/11/49/74e4a31de6abe70227fa1cb22d37-1612083.jpg!d');

    got.stream(resource)
        .on('error', err => console.log(err))
        .pipe(
            fs.createWriteStream('image.jpg')
        )
})();

```

**Comment by sayem314** [comment]
Can you send me the HTML of the challenge page?

**Comment by linaspasv** [comment]
Okay, so it seems my challenge page ends up in .on('error')

```javascript
const got = require('hooman');
const fs = require('fs');

(async () => {
    let resource = 'https://c.pxhere.com/images/11/49/74e4a31de6abe70227fa1cb22d37-1612083.jpg!d';

    got.stream(resource)
        .on('error', err => console.log(err.response.body))
        .pipe(
            fs.createWriteStream('image.jpg')
        )
})();
```


I get the follow output now.
[cf-challenge.txt](https://github.com/sayem314/hooman/files/4604302/cf-challenge.txt)

**Comment by linaspasv** [comment]
It seems this might be the issue why your hook at afterResponse is not being triggered and I am seeing the following results.

![image](https://user-images.githubusercontent.com/1407067/81482549-8713b780-9240-11ea-9d19-f5092e8fbb1d.png)

**Comment by sayem314** [comment]
I see `.streams()` are unsupported unfortunately. But did you try with `responseType: 'buffer'` as shown in test.js of hooman? Btw your HTML is okay, hooman should be able to solve it without issue.

https://github.com/sayem314/hooman/blob/master/test.js#L41-L48

**Comment by linaspasv** [comment]
First of all to make your library work with 'buffer' one needs to convert buffer to the string inside the afterResponse hook first.

```javascript
if (
          // If site is not hosted on cloudflare skip
          response.statusCode === 503 &&
          response.headers.server === "cloudflare" &&
          response.body.includes("jschl-answer")
        ) {
            let body = response.body instanceof Buffer
                ? response.body.toString()
                : response.body

            const data = await solve(response.url, body);

```

While this part is resolved I still get 415 (Unsupported Media Type) error when this line runs - https://github.com/sayem314/hooman/blob/9776a070fc12b2c69ce6169ceaf14671363c8dde/index.js#L42

**Comment by sayem314** [comment]
Convert is not necessary on hooks since it should match only when it's an HTML page. Something must be wrong on your end, I have tested it on multiple datacenter IP and VPN and for me, it works every time. Something must be wrong on your end :(

**Comment by andress134** [comment]
@sayem314 do u have discord?
HOW can improve this script use hooman

`const fs = require('fs'),
    CloudScraper = require('cloudscraper'),
    path = require('path');

const target = process.argv[2],
    time = process.argv[3],
    req_per_ip = process.argv[4];

let proxies = fs.readFileSync(process.argv[5], 'utf-8').replace(/\r/gi, '').split('\n').filter(Boolean);

function send_req() {
    let proxy = proxies[Math.floor(Math.random() * proxies.length)];

    let getHeaders = new Promise(function (resolve, reject) {
        CloudScraper({
            uri: target,
            resolveWithFullResponse: true,
            proxy: 'http://' + proxy,
            challengesToSolve: 10
        }, function (error, response) {
            if (error) {
                let obj_v = proxies.indexOf(proxy);
                proxies.splice(obj_v, 1);
                return console.log(error.message);
            }
            resolve(response.request.headers);
        });
    });

    getHeaders.then(function (result) {
        // Object.keys(result).forEach(function (i, e) {
        //     console.log(i + ': ' + result[i]);
        // });
        for (let i = 0; i < req_per_ip; ++i) {
            CloudScraper({
                uri: target,
                headers: result,
                proxy: 'http://' + proxy,
                followAllRedirects: false
            }, function (error, response) {
                if (error) {
                    console.log(error.message);
                }
            });
        }
    });
}`

**Comment by sayem314** [comment]
@andress134 can you be more specific what you are trying to achieve? Btw I guess your question is not related to this issue, for further discussion please open new issue with more details. Also your code was unreadable so I had to edit it a little.

Here is how you use proxy btw as per your code example.

```js
const fs = require('fs'),
  got = require('hooman'),
  path = require('path'),
  HttpsProxyAgent = require('https-proxy-agent');

const target = process.argv[2],
  time = process.argv[3],
  req_per_ip = process.argv[4];

let proxies = fs
  .readFileSync(process.argv[5], 'utf-8')
  .replace(/\r/gi, '')
  .split('\n')
  .filter(Boolean);

function send_req() {
  let proxy = proxies[Math.floor(Math.random() * proxies.length)];
  proxy = new HttpsProxyAgent('http://' + proxy);

  return new Promise((resolve, reject) => {
    got(target, {
      agent: {
        https: proxy,
      },
      cloudflareRetry: 10,
    })
      .then((response) => {
        console.log(response.body);
        resolve(response);
      })
      .catch((error) => {
        let obj_v = proxies.indexOf(proxy);
        proxies.splice(obj_v, 1);
        console.log(error.message);
        return reject(error.message);
      });
  });
}
```

Proxy docs: https://github.com/sindresorhus/got#proxies
Proxy module: https://www.npmjs.com/package/https-proxy-agent

**Comment by andress134** [comment]
> ```js
> const fs = require('fs'),
>   got = require('hooman'),
>   path = require('path'),
>   HttpsProxyAgent = require('https-proxy-agent');
> 
> const target = process.argv[2],
>   time = process.argv[3],
>   req_per_ip = process.argv[4];
> 
> let proxies = fs
>   .readFileSync(process.argv[5], 'utf-8')
>   .replace(/\r/gi, '')
>   .split('\n')
>   .filter(Boolean);
> 
> function send_req() {
>   let proxy = proxies[Math.floor(Math.random() * proxies.length)];
>   proxy = new HttpsProxyAgent('http://' + proxy);
> 
>   return new Promise((resolve, reject) => {
>     got(target, {
>       agent: {
>         https: proxy,
>       },
>       cloudflareRetry: 10,
>     })
>       .then((response) => {
>         console.log(response.body);
>         resolve(response);
>       })
>       .catch((error) => {
>         let obj_v = proxies.indexOf(proxy);
>         proxies.splice(obj_v, 1);
>         console.log(error.message);
>         return reject(error.message);
>       });
>   });
> }
> ```

i'm testing on   https://www.apotea.se/ 80

and is spamming  with 
Response code 503 (Service Unavailable)

**Comment by sayem314** [comment]
@andress134 the mentioned sites works fine on tests.

![image](https://user-images.githubusercontent.com/14138401/81502303-ff40b280-92fe-11ea-9f4d-6cee6ec79521.png)

And please don't continue any further discussion about this in this issue, create a new issue and I'm happy to assist you.

**Comment by sayem314** [comment]
Closing this issue as I was unable to re-produce. BTW I was also able to get `.stream()` to work, I will update the instruction on the readme.

**Comment by linaspasv** [comment]
@sayem314 thank you for your help. Looking forward to try this with ``.stream()``. :-)

**Comment by sayem314** [comment]
@linaspasv docs updated for stream https://github.com/sayem314/hooman#pipe-stream
