### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by andress134** [sayem314/hooman#4]
I get error 

node:30584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 611)

======
CODE 

```js
const fs = require('fs'),
  got = require('hooman'),
  path = require('path'),
  HttpsProxyAgent = require('https-proxy-agent');

const target = process.argv[2],
  time = process.argv[3],
  req_per_ip = process.argv[4];

let proxies = fs
  .readFileSync(process.argv[5], 'utf-8')
  .replace(/\r/gi, '')
  .split('\n')
  .filter(Boolean);

function send_req() {
  let proxy = proxies[Math.floor(Math.random() * proxies.length)];
  proxy = new HttpsProxyAgent('http://' + proxy);

  return new Promise((resolve, reject) => {
    got(target, {
      agent: {
        https: proxy,
      },
      cloudflareRetry: 10,
    })
      .then((response) => {
        console.log(response.body);
        resolve(response);
      })
      .catch((error) => {
        let obj_v = proxies.indexOf(proxy);
        proxies.splice(obj_v, 1);
        console.log(error.message);
        return reject(error.message);
      });
  });
}

setInterval(() => {
    send_req();
});
```

If i add 
`process.on('uncaughtException', (err) => {});
process.on('unhandledRejection', (err ) => {});`

will hide my errors but spamming with

`Response code 503 (Service Unavailable)`

nodejs - v14.2.0
OS : Debian 9
target test https://www.apotea.se/

// Sorry for bad my english, and if title is bad

**Comment by sayem314** [comment]
The issue was with `cloudflareRetry` and I have fixed it on `v1.1.1` https://github.com/sayem314/hooman/commit/d1f85cc988dd1de5c1683ba99fff2fd9e06af55e

Please update and run this example to test:

```js
const got = require(".");

function send_req(target) {
  return new Promise((resolve, reject) => {
    got(target, {
      cloudflareRetry: 10
    })
      .then(response => {
        console.log(response.body);
        resolve(response);
      })
      .catch(error => {
        console.log(error.message);
        return reject(error);
      });
  });
}

send_req("https://www.apotea.se/");
```

Also, note that you should specify interval delay in your example setInterval code.

**Comment by andress134** [comment]
> The issue was with `cloudflareRetry` and I have fixed it on `v1.1.1` [d1f85cc](https://github.com/sayem314/hooman/commit/d1f85cc988dd1de5c1683ba99fff2fd9e06af55e)
> 
> Please update and run this example to test:
> 
> ```js
> const got = require(".");
> 
> function send_req(target) {
>   return new Promise((resolve, reject) => {
>     got(target, {
>       cloudflareRetry: 10
>     })
>       .then(response => {
>         console.log(response.body);
>         resolve(response);
>       })
>       .catch(error => {
>         console.log(error.message);
>         return reject(error);
>       });
>   });
> }
> 
> send_req("https://www.apotea.se/");
> ```
> 
> Also, note that you should specify interval delay in your example setInterval code.

`Response code 503 (Service Unavailable)
(node:26370) UnhandledPromiseRejectionWarning: HTTPError: Response code 503 (Service Unavailable)
    at PromisableRequest.<anonymous> (/root/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26370) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by andress134** [comment]
> > The issue was with `cloudflareRetry` and I have fixed it on `v1.1.1` [d1f85cc](https://github.com/sayem314/hooman/commit/d1f85cc988dd1de5c1683ba99fff2fd9e06af55e)
> > Please update and run this example to test:
> > ```js
> > const got = require(".");
> > 
> > function send_req(target) {
> >   return new Promise((resolve, reject) => {
> >     got(target, {
> >       cloudflareRetry: 10
> >     })
> >       .then(response => {
> >         console.log(response.body);
> >         resolve(response);
> >       })
> >       .catch(error => {
> >         console.log(error.message);
> >         return reject(error);
> >       });
> >   });
> > }
> > 
> > send_req("https://www.apotea.se/");
> > ```
> > 
> > 
> > Also, note that you should specify interval delay in your example setInterval code.
> 
> `Response code 503 (Service Unavailable) (node:26370) UnhandledPromiseRejectionWarning: HTTPError: Response code 503 (Service Unavailable) at PromisableRequest.<anonymous> (/root/node_modules/got/dist/source/as-promise/index.js:124:28) at processTicksAndRejections (internal/process/task_queues.js:97:5) (Use `node --trace-warnings ...`to show where the warning was created) (node:26370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:26370) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

now work bypass, but spamming me with  this

`body, html {width: 100%; height: 100%; margin: 0; padding: 0}
.row-container {display: flex; width: 100%; height: 100%; flex-direction: column; background-color: blue; overflow: hidden;}
.first-row {background-color: lime; }
.second-row { flex-grow: 1; border: none; margin: 0; padding: 0; }
</style>
<div class="row-container">
  <iframe src="https://tarnkappe.info/when-digital-stones-fly-an-interview-with-free-boot-to/" class="second-row"></iframe>
</div>
Response code 403 (Forbidden)
Response code 403 (Forbidden)
Response code 403 (Forbidden)
Response code 403 (Forbidden)
Response code 403 (Forbidden)
<style>
body, html {width: 100%; height: 100%; margin: 0; padding: 0}
.row-container {display: flex; width: 100%; height: 100%; flex-direction: column; background-color: blue; overflow: hidden;}
.first-row {background-color: lime; }
.second-row { flex-grow: 1; border: none; margin: 0; padding: 0; }
</style>
<div class="row-container">
  <iframe src="https://tarnkappe.info/when-digital-stones-fly-an-interview-with-free-boot-to/" class="second-row"></iframe>
</div>
Response code 405 (Method Not Allowed)
Response code 405 (Method Not Allowed)
Response code 405 (Method Not Allowed)
Response code 405 (Method Not Allowed)
<style>
body, html {width: 100%; height: 100%; margin: 0; padding: 0}
.row-container {display: flex; width: 100%; height: 100%; flex-direction: column; background-color: blue; overflow: hidden;}
.first-row {background-color: lime; }
.second-row { flex-grow: 1; border: none; margin: 0; padding: 0; }
</style>
<div class="row-container">
  <iframe src="https://tarnkappe.info/when-digital-stones-fly-an-interview-with-free-boot-to/" class="second-row"></iframe>
</div>
<style>
body, html {width: 100%; height: 100%; margin: 0; padding: 0}
.row-container {display: flex; width: 100%; height: 100%; flex-direction: column; background-color: blue; overflow: hidden;}
.first-row {background-color: lime; }
.second-row { flex-grow: 1; border: none; margin: 0; padding: 0; }
</style>
`

**Comment by sayem314** [comment]
403 === captch

hooman doesn't handle captcha

**Comment by sayem314** [comment]
You can now solve captchas. Take a look at readme.

**Comment by andress134** [comment]
> You can now solve captchas. Take a look at readme.

What is wrong : https://pastebin.com/raw/2JuBBnBr if u can help me

**Comment by sayem314** [comment]
Code seems to be OK. Not sure what's wrong. Note that captcha cannot be solved on all sites.

**Comment by andress134** [comment]
tested on 2 websites with hcaptcha

https://shawty.club/
https://exitus.xyz

**Comment by sayem314** [comment]
![image](https://user-images.githubusercontent.com/14138401/81598036-7d2cb880-93e8-11ea-957f-58f14f032b70.png)

![image](https://user-images.githubusercontent.com/14138401/81598137-a77e7600-93e8-11ea-8178-09fc70eaaa1a.png)


They both work fine. Please verify your side of the code.

**Comment by andress134** [comment]
`(node:10255) UnhandledPromiseRejectionWarning: HTTPError: Response code 403 (Forbidden)
    at PromisableRequest.<anonymous> (/root/node_modules/got/dist/source/as-promise/index.js:124:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10255) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 170)`

**Comment by andress134** [comment]
> ![image](https://user-images.githubusercontent.com/14138401/81598036-7d2cb880-93e8-11ea-957f-58f14f032b70.png)
> 
> ![image](https://user-images.githubusercontent.com/14138401/81598137-a77e7600-93e8-11ea-8178-09fc70eaaa1a.png)
> 
> They both work fine. Please verify your side of the code.

with my changes https://pastebin.com/raw/aatxafV9 my 2captcha balance is going, but don't bypass, just spam my vps with this

`(node:10255) UnhandledPromiseRejectionWarning: HTTPError: Response code 403 (Forbidden)
    at PromisableRequest.<anonymous> (/root/node_modules/got/dist/source/as-promise/index.js:124:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10255) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 170)`
