### ISSUE TITLE
Upgrade cloudscraper to hooman using sockets

### ISSUE THREAD

**Issue by maximus99-art** [sayem314/hooman#5]
thank sir.
/fixed

**Comment by sayem314** [comment]
Please make your code format readable and provide more details. See markdown code syntax for js here https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by maximus99-art** [comment]
> Please make your code format readable and provide more details. See markdown code syntax for js here https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

https://pastebin.com/raw/dmX6Ff12 ORIGINAL script., using cloudscraper

my tried to edit : https://pastebin.com/raw/5mkJ6UrP
original script using cloudscraper get cookie and conect the ip to url, sending requests

**Comment by sayem314** [comment]
Can you provide an example URL you are trying on? It seems to work fine with this code.

```js
got(jsChallengePage)
  .then(response => {
    console.log(response.body);
  })
  .catch(error => {
    console.error(error);
  });
```

Also, strip any socket related code, this has nothing to do with hooman. Post only re-producible vanilla hooman code with example URL.

**Comment by maximus99-art** [comment]
> Can you provide an example URL you are trying on? It seems to work fine with this code.
> 
> ```js
> got(jsChallengePage)
>   .then(response => {
>     console.log(response.body);
>   })
>   .catch(error => {
>     console.error(error);
>   });
> ```
> 
> Also, strip any socket related code, this has nothing to do with hooman. Post only re-producible vanilla hooman code with example URL.

when im using proxies and random user agents, im received   Response code 403 (Forbidden) but website use  uam  : https://botflare.xyz
this is because bad proxies and cloudflare block it or idk
if im removing sockets, and just using 1 IP and 1 user agent  (my vps) bypass work
I tried many times, 6 times, 4 times work bypass 2 times get captcha code

Is posible  using anticaptcha or 2captcha with hooman? now is supporting just uam ?

im looking to upgrade this script to use hooman https://pastebin.com/raw/3mHBaRxX

i tried to change like this

`got(process.argv[2], {
  cloudflareRetry: 10
  })
  .then(response => {
  console.log(response.body);
  })
  .catch(error => {
  console.log(error.message);
  },
  headers: {
    'cookie': cookies[ourproxy] || '',
    'user-agent': 'Ubuntu Chromium/34.0.1847.116 Chrome/34.0.1847.116 Safari/537.36'
  },
  proxy: 'http://' + ourproxy
}, function(error, response, body) {`

but just get error

**Comment by sayem314** [comment]
You are not supposed to use random user-agents, hooman takes care of that. Changing UA frequently triggers you as a bot. Also, hooman doesn't handle 403 (captcha) yet but it's planned.

**Comment by maximus99-art** [comment]
https://pastebin.com/raw/j66bACp4 here are my changes, some wrong ?

i received  error

`UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 62)`

**Comment by sayem314** [comment]
Do not provide `cookie` or `user-agent` maybe since hooman automatically handles it.

**Comment by sayem314** [comment]
Also, proxy usage is wrong. Please read the docs first.
https://github.com/sindresorhus/got/blob/master/readme.md#proxies
