### ISSUE TITLE
Unable to solve challenge

### ISSUE THREAD

**Issue by 0Franky** [sayem314/hooman#6]
Hi,
I'm trying to get html from this site:
https://www.netfreex.club/
but I receive an error. It looks like the challenge can't be solved.

I can see through the html the challege __cf_chl_jschl_tk__ , but this site:
https://ilgeniodellostreaming.tw/?s=casa+di+carta (accessible only by Italian IP)
use the same challenge, and here it works.

**Comment by sayem314** [comment]
Your mentioned site throws captcha after solving js-challenge. It works if you provide a 2captcha API key. And your Italian sites work globally it seems.

![image](https://user-images.githubusercontent.com/14138401/81668010-d981ed80-9465-11ea-8bf5-63c42446e986.png)
