### ISSUE TITLE
Consume too much balance

### ISSUE THREAD

**Issue by andress134** [sayem314/hooman#9]
#### What would you like to discuss?

Okay, the problem is the following, my script works perfectly, bypasses, but consumes a lot of balance from the 2captcha account, in 1 minute it consumed me $ 3
How could I make him consume less, it seems he takes money for every request

My old script based on cloudscraper, used only 0.02 to solve captcha, once, but using hooman seems to consume a lot for each request

I'm sorry for my  bad english

this is my code

`const fs = require('fs'),
  hooman = require('hooman'),
  path = require('path'),
  HttpsProxyAgent = require('https-proxy-agent');

const target = process.argv[2],
  time = process.argv[3],
  req_per_ip = process.argv[4];

function send_req() {

  return new Promise((resolve, reject) => {
    hooman.get(target, {
      captchaKey: 'my-key',
        });
      })
      .catch((error) => {
        console.log(error.message);
        return reject(error.message);
      });
}

setInterval(() => {
    send_req();
});`
#### Checklist

- [x] I have read the hooman and got documentation.

**Comment by sayem314** [comment]
This is probably because you have flooded with requests before initializing cookie. But wait, I'll work on it.

**Comment by sayem314** [comment]
Fixed on v1.2.1 but:

> Note that if you make multiple request at once only the first request will be served without error. This is so that you don't end up paying extra for captcha solving. If you would like to fetch more than one request at a time, first solve captcha and then make rest of your request after cookie is set.
